version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: backend/Dockerfile  
    ports:
      - "5000:5000"  
    env_file:
      - backend/.env  
    networks:
      - app-network
    depends_on:
      - mongodb  

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    environment:
      - REACT_APP_API_URL=http://backend:5000  
    networks:
      - app-network
    depends_on:
      - backend  

  mongodb:
    image: mongo:latest  
    container_name: mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  
    networks:
      - app-network

volumes:
  mongo_data:  

networks:
  app-network:
    driver: bridge  